
server:
  port: 8083

spring:
  application:
    name: Practice-RocketMq

rocketmq:
  name-server: 150.158.170.34:9876
  producer:
    group: GROUP_ZACHARY_TEST
    send-message-timeout: 3000  # 发送消息超时时间，单位：毫秒。默认为 3000 。
    retry-times-when-send-failed: 2   # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed:   2 # 异步发送消息时，失败重试次数。默认为 2 次。
    compress-message-body-threshold: 4096 # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    max-message-size: 4194304 # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    retry-next-server: false # 发送消息给 broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
  consumer:
    group: GROUP_ZACHARY_TEST
